### ISSUE TITLE
Synchronize required cutouts in panels for XY mounts (front pulleys, motor mounts)

### ISSUE THREAD

**Issue by PStibbons2K** [MirageC79/HevORT#19]
Hi Olivier,

currently the panels for the different XY variants (Std, HT, HD) all require different sizes for the cutouts - to be able to use the same panels for all variants would be really nice!

I think the largest cutout is needed for HD12, on the left pulley the lower edge is flush with the extrusion - STD und HT variants both use more on the left side.

![image](https://user-images.githubusercontent.com/5845733/163048800-10f27b92-0747-4334-8f6f-dcbae822bdfd.png)

i could try to redesign the left pulley mount for the STD variant :)

Kind regards,
Martin

**Comment by MirageC79** [comment]
Yes, that is a good point.  I thought of this at one point and was teared between functionality and interchangeability.  Perhaps an adapter plate of filler contour of some sort with provision holes in the smallest designs.   Keep me posted on your proposal ;)

**Comment by PStibbons2K** [comment]
First idea for the footprint of the front pulley mounts would be something like this:

![image](https://user-images.githubusercontent.com/5845733/163057001-1c4b8748-616d-420d-a05e-1efe58bbfd41.png)

I'll try and trace the belt paths for the different variants tomorrow, maybe even a unified pulley mount with an adapter for the different belt paths would be possible :)

**Comment by PStibbons2K** [comment]
If i got the different belt paths correct a unified pulley mount should be possible:

![image](https://user-images.githubusercontent.com/5845733/163186517-180d3c80-f0b4-488b-be6e-5922fc6d6bce.png)

Above and below the belts there is enough room for a secure mount :)

**Comment by PStibbons2K** [comment]
How about moving the Y Sensor bracket to the right pulley mount? That would simplify the wiring for the probe.

My prototype is still under development, at least the sketch on paper is taking form!

**Comment by PStibbons2K** [comment]
Not quite there - but the basic idea would be to have a unified mount attached to the frame and custom cartridges for the different XY-Versions.

The mounting holes around the opening are for M4 heat inserts (this kind or similar: https://www.amazon.de/dp/B07YSV66Y5 ) to mount the cartridges.

![image](https://user-images.githubusercontent.com/5845733/164946634-9024ae97-2646-40a7-8a9e-d6fb6254fecd.png)

Still very rough and without any fancy design elements ;)

**Comment by MirageC79** [comment]
As we are looking at the next version of the HevORT, this is something that we will consider.  But for now, there are no plan to modify existing release to harmonize their footprint on enclosure panel.

Thank you.
