### ISSUE TITLE
Electronics BOM misplaced download icon

### ISSUE THREAD

**Issue by WallK** [MirageC79/HevORT#21]
On https://docs.hevort.com/#/pages/component-selection?id=_4-electronics :

AR: Download icon on "BOM - Web" button
ER: Download icon on "BOM Download" button

![image](https://user-images.githubusercontent.com/4513545/163208158-c1fb13f3-1b96-46ad-b8d1-47edb161abf6.png)

**Comment by MarvinBeym** [comment]
I don't see a misplaced icon

**Comment by MarvinBeym** [comment]
Will fix it later
