### ISSUE TITLE
HD12: Right Motor mount sticking out of the case

### ISSUE THREAD

**Issue by PStibbons2K** [MirageC79/HevORT#34]
Hey Mirage,

found an issue with the right motor mount for the HD12 gantry - the mount is sticking out from the rear of the case, in the AcidBee CAD-File there seems to be a variant that stays inside the case - is there an update for HD12 missing?

Thanks a lot!

Kind regards, 
Martin

![gantry1](https://user-images.githubusercontent.com/5845733/183309499-241464a0-f80e-4932-9dcc-2dbefbe54d6e.png)
![gantry2](https://user-images.githubusercontent.com/5845733/183309501-daaab76e-0c19-4660-a1fa-03421e2693de.png)

**Comment by MirageC79** [comment]
Hello Martin, thanks for highlighting this issue.  I have exported the modified CAD file from Acid Bee to STL here:
https://github.com/MirageC79/HevORT/blob/master/files/STL/HD12/HD12_MotorMount_RH_ForEnclosure_BodyV1.5.stl

Thank you
