### ISSUE TITLE
Recipe for Printer Calibration

### ISSUE THREAD

**Issue by twistedbeholder** [MirageC79/HevORT#42]
http://docs.hevort.com/#/printercalibration is not a valid link

**Comment by MarvinBeym** [comment]
Why would it?

**Comment by twistedbeholder** [comment]
Because it is on your documentation page and just goes to an error page.


This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed
by Frank Leach. If you have received this email in error please notify the
system manager. This message contains confidential information and is
intended only for the individual named by Frank Leach. If you are not the
named addressee you should not disseminate, distribute or copy this e-mail.
Please notify the sender immediately by e-mail if you have received this
e-mail by mistake and delete this e-mail from your system. If you are not
the intended recipient you are notified that disclosing, copying,
distributing or taking any action in reliance on the contents of this
information is strictly prohibited.  If you are any member of any
government you are assessed a fee of $1,000,000.00 in gold bullion each
time this information is opened, viewed, used, referenced, or thought about
in any way. Please contact Frank leach at ***@***.*** for
shipping instructions.



"There is no such thing as a little freedom. Either you are all free, or
you are not free."

- Walter Cronkite

**Comment by MarvinBeym** [comment]
where is it mentioned?

**Comment by MarvinBeym** [comment]
Found it: https://github.com/MirageC79/HevORT/blob/34970d0e283402a5e1a50d451e5098ccbe7e8860/docs/pages/how-to-print-parts.md
