### ISSUE TITLE
STP file for wobblex

### ISSUE THREAD

**Issue by termlimit** [MirageC79/HevORT#44]
Looking for a cad file for the WS12 WobbleX. I may have missed it, but I don't see it anywhere in the cad file. The CAD file contains the 3d printed version. Thank you!

**Comment by MarvinBeym** [comment]
WobbleX is closed source

**Comment by termlimit** [comment]
Was not aware of that, but an STP or stl could be provided. Anything to suffice for modelling purposes.

**Comment by MirageC79** [comment]
Printable version of wobble rings is included in the CAD for 2.6.  WobbleX files are not available.
