### ISSUE TITLE
Carriage Mounting Screws on the Metal Printhead

### ISSUE THREAD

**Issue by O-to-the-o** [MirageC79/HevORT#50]
According to the VZ Documentation for the Mellow Metal Printhead [VZ Documentation for the Mellow Metal Printhead ](https://github.com/VzBoT3D/Vz-Printhead-CNC/tree/main/Instructions)used in this 
[Vez Metal Print Head & Goliath SHORT](https://hotmail114573.autodesk360.com/g/shares/SHd38bfQT1fb47330c996f6ad64dd2a993e2) and this [Vez Metal Print Head & Goliath LONG](https://hotmail114573.autodesk360.com/g/shares/SHd38bfQT1fb47330c99cf72fbff5c6debe4) cad model should be 5mm or 4mm I'd reccomend to change it to 4mm as the kit comes with 4 of them

**Comment by MirageC79** [comment]
CAD files for both versions have been fixed.  Screw attaching the print head to the MGN9 block have been replaced by M3X4mm ultra low profile heat cap screws.
![image](https://github.com/MirageC79/HevORT/assets/29920140/81eef5e2-25a2-42b3-b428-b949241f0d41)
