### ISSUE TITLE
Add Diameter for the Dowel Pins for the Acid Bee Enclousre in BOM and CAD 

### ISSUE THREAD

**Issue by O-to-the-o** [MirageC79/HevORT#51]
The Diameter for the Dowel pin is missing in the BOM and CAD file (here only in nameing the part)
https://docs.hevort.com/bom/BOM_Enclosure_AcidBee.htm

For now Dowel pins need to be 60mm*5mm

**Comment by MirageC79** [comment]
Thanks for reporting 😊
Change has been made to BOM
Closing Ticket.
![image](https://github.com/MirageC79/HevORT/assets/29920140/e45be871-ae68-4222-abad-bacea0ff2c66)
