### ISSUE TITLE
HD9 and HD12 Suggestion: Allow pullies/idlers with wider flanges.

### ISSUE THREAD

**Issue by Megamannen** [MirageC79/HevORT#6]
The HD9 and HD12 BOM (and printed parts) use an E3 specified idler and pullies that have a flange diameter of 15mm

The STD version uses pulleys with a 18mm flange

A lot of vendors have the 9/10mm width and 12mm pulleys with the flange size 18mm, they doesn't fit, seems to be missing 0.5-1.5mm clearance (have not tested all locations)

**Comment by MirageC79** [comment]
As of the the official design makes use of the Gates specifications for pulleys.  You can try to modify the CADs to suit your needs.
